import os
import numpy as np
import pandas as pd

# Evidently 0.7.x uses the top-level evidently namespace
from evidently import Report
from evidently.presets import DataDriftPreset


def run_drift_analysis(rfm_csv_path="data/rfm_features.csv", output_html="reports/drift_report.html"):
    """
    Loads reference data (data/rfm_features.csv), generates a synthetic 'current'
    dataset with realistic data drift (simulating customer inactivity), and
    generates an Evidently AI HTML drift report.

    NOTE: The 'current' dataset is synthetically generated by applying a realistic
    shift to the reference data — simulating customers going quiet over time
    (Recency increases) and purchasing less (Frequency drops slightly). In a real
    production system, this would be replaced with actual incoming inference data.
    """
    if not os.path.exists(rfm_csv_path):
        raise FileNotFoundError(f"Reference dataset not found at {rfm_csv_path}")

    # 1. Load reference dataset (training distribution)
    reference_data = pd.read_csv(rfm_csv_path)
    cols = ["Recency", "Frequency", "Monetary"]
    reference_df = reference_data[cols].copy()

    # 2. Simulate 'current' production dataset with realistic drift
    np.random.seed(42)
    current_df = reference_df.copy()

    # Shift Recency upwards by 15-45 days → customers going quiet
    current_df["Recency"] = current_df["Recency"] + np.random.randint(15, 45, size=len(current_df))

    # Slightly reduce Frequency → less repeat purchasing
    freq_drop = np.random.choice([0, 1], size=len(current_df), p=[0.6, 0.4])
    current_df["Frequency"] = np.maximum(1, current_df["Frequency"] - freq_drop)

    print(f"Reference dataset size: {len(reference_df)}")
    print(f"Simulated current dataset size: {len(current_df)}")
    print(f"Avg Recency shift: reference={reference_df['Recency'].mean():.1f}  current={current_df['Recency'].mean():.1f}")

    # 3. Build Evidently Report with DataDriftPreset (0.7.x API)
    report = Report(metrics=[DataDriftPreset()])
    my_run = report.run(reference_data=reference_df, current_data=current_df)

    # 4. Save HTML report
    os.makedirs(os.path.dirname(output_html), exist_ok=True)
    my_run.save_html(output_html)
    print(f"\u2705  Data drift report saved: {output_html}")


if __name__ == "__main__":
    run_drift_analysis()
